"1.4548457750964128 0.30684396215251447
"
andProjects/Algos2/src/plot/practice/drawGraphics.py': [Errno 2] No such file or directory
"
100000,"23

Traceback (most recent call last):
  File ""/home/kudrix/GolandProjects/Algos2/src/plot/practice/drawSinglePlotPractice.py"""," line 48"," in <module>
    arrYInt.append(int(arr[1]))
                       ~~~^^^
IndexError: list index out of range
"
gnore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/kudrix/.local/lib/python3.12/site-packages/matplotlib/figure.py"""," line 3395"," in savefig
    self.canvas.print_figure(fname"," **kwargs)
  File ""/home/kudrix/.local/lib/python3.12/site-packages/matplotlib/backend_bases.py"""," line 2204"," in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File ""/home/kudrix/.local/lib/python3.12/site-packages/matplotlib/backend_bases.py"""," line 2054"," in <lambda>
    print_method = functools.wraps(meth)(lambda *args"," **kwargs: meth(
                                                                 ^^^^^
  File ""/home/kudrix/.local/lib/python3.12/site-packages/matplotlib/backends/backend_agg.py"""," line 496"," in print_png
    self._print_pil(filename_or_obj"," ""png"""," pil_kwargs"," metadata)
  File ""/home/kudrix/.local/lib/python3.12/site-packages/matplotlib/backends/backend_agg.py"""," line 445"," in _print_pil
    mpl.image.imsave(
  File ""/home/kudrix/.local/lib/python3.12/site-packages/matplotlib/image.py"""," line 1676"," in imsave
    image.save(fname"," **pil_kwargs)
  File ""/usr/lib64/python3.12/site-packages/PIL/Image.py"""," line 2456"," in save
    fp = builtins.open(filename"," ""w+b"")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/home/kudrix/GolandProjects/Algos2/image/practice/AVL Дерево.png'
"
^^^^^^^
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/home/kudrix/GolandProjects/Algos2/image/practice/AVL Дерево.png'
"
